#########BOARD#########
board = [
  #row1
  [
    {"word": 3, "letter": 1, "value": "", "color": "orange"}, 
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 3, "letter": 1, "value": "", "color": "orange"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 3, "letter": 1, "value": "", "color": "orange"}
  ],
  #row2
  [
    {"word": 1, "letter": 1, "value": "", "color": "white"}, 
    {"word": 2, "letter": 1, "value": "", "color": "red"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 3, "value": "", "color": "green"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 3, "value": "", "color": "green"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 2, "letter": 1, "value": "", "color": "red"},
    {"word": 1, "letter": 1, "value": "", "color": "white"}
  ],
  #row3
  [
    {"word": 1, "letter": 1, "value": "", "color": "white"}, 
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 2, "letter": 1, "value": "", "color": "red"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 2, "letter": 1, "value": "", "color": "red"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"}
  ],
  #row4
  [
    {"word": 1, "letter": 2, "value": "", "color": "blue"}, 
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 2, "letter": 1, "value": "", "color": "red"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 2, "letter": 1, "value": "", "color": "red"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"}
  ],
  #row5
  [
    {"word": 1, "letter": 1, "value": "", "color": "white"}, 
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 2, "letter": 1, "value": "", "color": "red"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 2, "letter": 1, "value": "", "color": "red"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"}
  ],
  #row6
  [
    {"word": 1, "letter": 1, "value": "", "color": "white"}, 
    {"word": 1, "letter": 3, "value": "", "color": "green"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 3, "value": "", "color": "green"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 3, "value": "", "color": "green"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 3, "value": "", "color": "green"},
    {"word": 1, "letter": 1, "value": "", "color": "white"}
  ],
  #row7
  [
    {"word": 1, "letter": 1, "value": "", "color": "white"}, 
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"}
  ],
  #row8
  [
    {"word": 3, "letter": 1, "value": "","color": "orange"}, 
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 2, "letter": 1, "value": "", "color": "red"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 3, "letter": 1, "value": "", "color": "orange"}
  ],
  #row9
  [
    {"word": 1, "letter": 1, "value": "", "color": "white"}, 
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"}
  ],
  #row10
  [
    {"word": 1, "letter": 1, "value": "", "color": "white"}, 
    {"word": 1, "letter": 3, "value": "", "color": "green"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 3, "value": "", "color": "green"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 3, "value": "", "color": "green"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 3, "value": "", "color": "green"},
    {"word": 1, "letter": 1, "value": "", "color": "white"}
  ],
  #row11
  [
    {"word": 1, "letter": 1, "value": "", "color": "white"}, 
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 2, "letter": 1, "value": "", "color": "red"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 2, "letter": 1, "value": "", "color": "red"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"}
  ],
  #row12
  [
    {"word": 1, "letter": 2, "value": "", "color": "blue"}, 
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 2, "letter": 1, "value": "", "color": "red"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 2, "letter": 1, "value": "", "color": "red"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"}
  ],
  #row13
  [
    {"word": 1, "letter": 1, "value": "", "color": "white"}, 
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 2, "letter": 1, "value": "", "color": "red"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 2, "letter": 1, "value": "", "color": "red"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"}
  ],
  #row14
  [
    {"word": 1, "letter": 1, "value": "", "color": "white"}, 
    {"word": 2, "letter": 1, "value": "", "color": "red"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 3, "value": "", "color": "green"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 3, "value": "", "color": "green"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 2, "letter": 1, "value": "", "color": "red"},
    {"word": 1, "letter": 1, "value": "", "color": "white"}
  ],
  #row15
  [
    {"word": 3, "letter": 1, "value": "", "color": "orange"}, 
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 3, "letter": 1, "value": "", "color": "orange"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 2, "value": "", "color": "blue"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 1, "letter": 1, "value": "", "color": "white"},
    {"word": 3, "letter": 1, "value": "", "color": "orange"}
  ]
]

tiles = [
    "A", "A", "A", "A", "A", "A", "A", "A", "A", 
    "B", "B", 
    "C", "C", 
    "D", "D", "D", "D", 
    "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E", "E",
    "F", "F",
    "G", "G", "G",
    "H", "H",
    "I", "I", "I", "I", "I", "I", "I", "I", "I",
    "J",
    "K",
    "L", "L", "L", "L",
    "M", "M",
    "N", "N", "N", "N", "N", "N",
    "O", "O", "O", "O", "O", "O", "O", "O",
    "P", "P",
    "R", "R", "R", "R", "R", "R", 
    "S", "S", "S", "S",
    "T", "T", "T", "T", "T", "T",
    "U", "U", "U", "U",
    "V", "V",
    "W", "W",
    "X",
    "Y", "Y",
    "Z",
    "?", "?"
]

#  points = {
#     "A": 1,
#     "B": 3,
#     "C": 3,
#     "D": 2,
#     "E": 1,
#     "F": 4,
#     "G": 2,
#     "H": 4,
#     "I": 1,
#     "J": 8,
#     "K": 5,
#     "L": 1,
#     "M": 3,
#     "N": 1,
#     "O": 1,
#     "P": 3,
#     "Q": 10,
#     "R": 1,
#     "S": 1,
#     "T": 1,
#     "U": 1,
#     "V": 4,
#     "W": 4,
#     "X": 8,
#     "Y": 4,
#     "Z": 10,
#     "?": 0
# }

game = Game.create(board: board, tiles: tiles)